on:
  # push:
  #    branches: ["main", "dev"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: echo 42
      - name: step 2
        run: ls -l -a
