on:
  # push:
  #    branches: ["main", "dev"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: echo 42
      - name: step 2
        run: ls -l -a
      - name: step 3
        uses: actions/checkout@v5
      - name: step 4
        run: ls -l -a
      - name: step 5
        uses: actions/setup-dotnet@v5.0.0
        with:
          # Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x, 3.x, 6.0.2xx
          dotnet-version: 8.x
      - name: step 6
        run: dotnet restore
      - name: step 7
        run: dotnet build -c release
      - name: step 8
        run: dotnet publish -o ./build
      - name: step 9
        run: ls ./build -l -a
      - name: step 10
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: step 1
        uses: actions/download-artifact@v4
        with:
          name: build
      - name: step 2
        run: ls -l -a
      - name: step3
        uses: pontago/lftp-deploy-action@v1.0.1
        with:
          host: example.com 
          username: ${{vars.FTP_USERNAME}} 
          password: ${{secrets.FTP_PASSWORD}}
        
        






        
