on:
  # push:
  #    branches: ["main", "dev"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: echo 42
      - name: step 2
        run: ls -l -a
      - name: step 3
        uses: actions/checkout@v5
      - name: step 4
        run: ls -l -a
      - name: step 5
        uses: actions/setup-dotnet@v5.0.0
        with:
          # Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x, 3.x, 6.0.2xx
          dotnet-version: 8.x
      - name: step 6
        run: dotnet restore
      - name: step 7
        run: dotnet build -c release
      - name: step 8
        run: dotnet publish -o ./build
      - name: step 4
        run: ls ./build -l -a






        
