on:
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Login
        uses: docker/login-action@v3.6.0
        with:
          # Username used to log against the Docker registry
          username: khunly1982
          # Password or personal access token used to log against the Docker registry
          password: ${{secrets.DOCKER_PWD}}
      - name: Build and push
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./DemoCICD
          push: true
          tags: khunly1982/democicd
        
